export default {
    SIGN_IN: 'sign_in',
    SIGN_IN_ERROR: 'sign_in_error',
    SIGN_OUT: 'sign_out',
    SIGN_OUT_ERROR: 'sign_out_error',
    SIGN_UP: 'sign_up',
    SIGN_UP_ERROR: 'sign_up_error',
    GET_USERNAME: 'get_username',
    GET_USERNAME_ERROR: 'get_username_error',
    STATS: 'get_user_stats',
    STATS_ERROR: 'get_user_stats_error',
    GET_USER_MEDIA: 'get_user_media',
    GET_USER_MEDIA_ERROR: 'get_user_media_error',
    GET_LANDING_MEDIA: 'get_landing_media',
    GET_LANDING_MEDIA_ERROR: 'get_landing_media_error',
    CREATE_COMMENT: 'create_comment',
    CREATE_COMMENT_ERROR: 'create_comment_error',
    LIKE_MEDIA: 'like_media',
    LIKE_MEDIA_ERROR: 'like_media_error',
    UNFOLLOW_USER: 'unfollow_user',
    UNFOLLOW_USER_ERROR: 'unfollow_user_error',
    GET_STORIES: 'get_stories',
    GET_STORIES_ERROR: 'get_stories_error',
    GET_STORIES_MEDIA: 'get_stories_media',
    GET_STORIES_MEDIA_ERROR: 'get_stories_media_error',


}